config/routes.rb
Rails.application.routes.draw do
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'homes#index'
  get 'admins' => 'admins#index', :as => 'admin_root'
  get 'undangan/:id' => 'bridegrooms#index'
  devise_for :users, :path => '', :path_names => { :sign_in => "login", :sign_out => "logout", :sign_up => "register" }
  namespace :admin do    
    resources :users    
    resources :user_groups
    resources :brides    
    resources :grooms
    resources :invited_guests    
    resources :weedings    
    resources :weeding_photos    
  end

end

app/models/action_model.rb
class ActionModel < ApplicationRecord
    belongs_to :controller_model
	has_and_belongs_to_many :user_groups, join_table: "action_models_user_groups"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bride.rb
class Bride < ApplicationRecord
    belongs_to :user, required: false, dependent: :destroy
    has_one_attached :image
end

app/models/controller_model.rb
class ControllerModel < ApplicationRecord
    has_many :action_models
end

app/models/groom.rb
class Groom < ApplicationRecord
    belongs_to :user, required: false, dependent: :destroy
    has_one_attached :image
end

app/models/invited_guest.rb
class InvitedGuest < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :user_group

  extend FriendlyId
  friendly_id :name, use: :slugged
  
  def has_priviledge(controller_name, action_name)
    @not_authorized = true

    self.user_group.action_models.each do |action_model|
      if (action_model.controller_model.path == controller_name && action_model.path == action_name)
        @not_authorized = false
      end

      break if ! @not_authorized
    end

    if (! @not_authorized || self.user_group.super == 1)
      true
    else
      false 
    end
  end
end

app/models/user_group.rb
class UserGroup < ApplicationRecord
    has_and_belongs_to_many :action_models, join_table: "action_models_user_groups"
end

app/models/weeding.rb
class Weeding < ApplicationRecord
    
    HOURS_DETAIL = [["--Pilih Jam--", ""],["00:00", 0] ,["01:00", 1], ["02:00", 2], ["03:00", 3], ["04:00", 4], ["05:00", 5], ["06:00", 6], ["07:00", 7], ["08:00", 8], ["09:00", 9], ["10:00", 10], 
                                    ["11:00", 11], ["12:00", 12], ["13:00", 13], ["14:00", 14], ["15:00", 15], ["16:00", 16], ["17:00", 17], ["18:00", 18],
                                    ["20:00", 20], ["21:00", 21], ["22:00", 22], ["23:00", 23]]
                                    
    HOURS = [["--Pilih Jam--", ""], ["07:00", 7], ["08:00", 8], ["09:00", 9], ["10:00", 10], 
            ["11:00", 11], ["12:00", 12], ["13:00", 13], ["14:00", 14], ["15:00", 15], ["16:00", 16], 
            ["17:00", 17], ["18:00", 18], ["19:00", 19], ["20:00", 20], ["21:00", 21], ["22:00", 22], ["23:00", 23]]

    has_many :weeding_photos
end

app/models/weeding_photo.rb
class WeedingPhoto < ApplicationRecord
    has_one_attached :image
end

app/controllers/admin/invited_guests_controller.rb
class Admin::InvitedGuestsController < ApplicationController
    before_action :authenticate_user!
    # before_action :authorize_user
    before_action :set_invited_guest, only: [:show, :edit, :update, :destroy]
    layout "admin"

    def index
        @invited_guests = InvitedGuest.order("name DESC")
    end

    def new
        @invited_guest = InvitedGuest.new

        respond_to do |format|
            format.html # new.html.erb
            format.xml  { render :xml => @invited_guest }
        end
    end

    def show 

        respond_to do |format|
            format.html # show.html.erb
            format.xml  { render :xml => @invited_guest }
        end
    end

    def create
        @invited_guest = InvitedGuest.new(invited_guest_params)

        respond_to do |format|
            if @invited_guest.save
            
            format.html { redirect_to(:controller => 'invited_guests') }
            format.xml  { render :xml => @invited_guest, :status => :created, :invited_guest => @invited_guest }
            else
            format.html { render :action => "new" }
            format.xml  { render :xml => @invited_guest.errors, :status => :unprocessable_entity }
            end
        end
    end

    def edit 
    end

    def update 

        respond_to do |format|
            if @invited_guest.update_attributes(invited_guest_params)
            
            format.html { redirect_to(:controller => 'invited_guests') }
            format.xml  { head :ok }
            else
            format.html { render :action => "edit" }
            format.xml  { render :xml => @invited_guest.errors, :status => :unprocessable_entity }
            end
        end
    end

    def destroy
        @invited_guest.destroy

        respond_to do |format|
            format.html { redirect_to(:controller => 'invited_guests') }
            format.xml  { head :ok }
        end
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_invited_guest
        @invited_guest = InvitedGuest.find(params[:id])
    end


    def invited_guest_params
        params.require(:invited_guest).permit(:number, :name, :weeding_id, :phone, :email, :total_guest, :attend, :table_number, :invitation_has_been_send, :checkin, :start_invitation_hour, :end_invitation_hour)
    end
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
    before_action :authenticate_user!
    layout "admin"
    
	def index
		
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
	protect_from_forgery with: :null_session

	layout :layout_by_resource
	
	before_action :controller_model


	  def controller_model
	    @months = ["", "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Jul", "Agustus", "September", "Oktober", "November", "Desember"]
	    @days = ["Minggu", "Senin", "Selasa", "Rabu", "Kamis", "Jum'at", "Sabtu"]
	    Time.zone = "Jakarta"
	  end
	  
	  def layout_by_resource
		if devise_controller?
		  if resource_name == :user
			"login"
		  end
		else
		  "application"
		end
	   end
	  
	  def after_sign_in_path_for(resource_or_scope)
		  if resource_or_scope.is_a?(Admin)
		  admin_root_path    
		else
		  super
		end
	  end
	  
	  def after_sign_out_path_for(resource_or_scope)
		if resource_or_scope.to_s == "admin"
		  new_admin_session_path
		else
		  root_path
		end
	  end

	  def authorize_user
	    if current_user.has_priviledge(params[:controller], params[:action])
	      true
	    else
	      redirect_to admin_root_path, notice: "You're not authorized to access the page"
	    end
	  end
end

app/controllers/bridegrooms_controller.rb
class BridegroomsController < ApplicationController
    layout "application"

    def index

		@user = User.friendly.find(params[:id])
		@groom = Groom.find_by_user_id(@user.id)
		@bride = Bride.find_by_user_id(@user.id)		
		@weeding = Weeding.find_by_user_id(@user.id)
		# render json: @weeding
	end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
    # before_action :authenticate_user!, only: [:index]
	layout "application_default"
	
	def index
		@months = ["Januari", "Februari", "Maret", "April", "Mei", "Juni", "Jul", "Agustus", "September", "Oktober", "November", "Desember"];		
	end	

end

app/helpers/admin/brides_helper.rb
module Admin::BridesHelper
end

app/helpers/admin/grooms_helper.rb
module Admin::GroomsHelper
end

app/helpers/admin/invited_guests_helper.rb
module Admin::InvitedGuestsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bridegrooms_helper.rb
module BridegroomsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/invited_guests/_form.html.erb
<%= content_for :js_script do %> 
   <!-- Select2 -->
    <script>
        $(function(){
            $('.selectpicker').selectpicker();
        });    
    </script>
<% end %>

<%= form_for([:admin, @invited_guest], html: {class: "form-horizontal"}) do |f| %>
    <% if @invited_guest.errors.any? %>
        <div id="error_explanation">
        <h2><%= pluralize(@invited_guest.errors.count, "error") %> prohibited this user from being saved:</h2>
        <ul>
        <% @invited_guest.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
        </ul>
        </div>
    <% end %>

    <div class="form-group row">
        <div class="col-md-2">
            <label class="form-control-label" for="l0">Nama<span style="color: red">*</span></label>
        </div>
        <div class="col-md-10">
            <%= f.text_field :name, class: "form-control", :required => true %>
        </div>
    </div>

    <div class="form-group row">
        <div class="col-md-2">
            <label class="form-control-label" for="l0">No Telepon<span style="color: red">*</span></label>
        </div>
        <div class="col-md-10">
            <%= f.text_field :phone, class: "form-control", :required => true %>
        </div>
    </div>

    <div class="form-group row">
        <div class="col-md-2">
            <label class="form-control-label" for="l0">Email<span style="color: red">*</span></label>
        </div>
        <div class="col-md-10">
            <%= f.text_field :email, class: "form-control", :required => true %>
        </div>
    </div>

    <div class="form-group row">
        <div class="col-md-2">
            <label class="form-control-label" for="l0">Total Tamu<span style="color: red">*</span></label>
        </div>
        <div class="col-md-10">
            <select class="form-control selectpicker" id="invited_guest_total_guest" name="invited_guest[total_guest]">
                <option value="">-- Jumlah Tamu --</option>
                    <option value="1">1</option>                    
                    <option value="2">2</option>                    
            </select>
        </div>
    </div>

    <div class="form-group row">
        <div class="col-md-2">
            <label class="form-control-label" for="l0">Status Kedatangan<span style="color: red">*</span></label>
        </div>
        <div class="col-md-10">
            <select class="form-control selectpicker" id="invited_guest_checkin" name="invited_guest[checkin]">
                <option value="">-- Status Kedatangan --</option>
                    <option value="0">Tidak Datang</option>                    
                    <option value="1">Datang</option>                    
            </select>
        </div>
    </div>

    <div class="form-group row">
        <div class="col-md-2">
            <label class="form-control-label" for="l0">Jam Datang<span style="color: red">*</span></label>
        </div>
        <div class="col-md-4">
            <label class="input-group">
                <%= f.select :start_invitation_hour, Weeding::HOURS, {}, {'data-placeholder': '--Pilih Jam Selesai Meeting--', class: 'form-control selectpicker', 'data-live-search': 'true'} %>
                <span class="input-group-addon">
                    <i class="icmn-clock"></i>
                </span>
            </label>                                
        </div>
        <div class="col-md-2">
            <label class="form-control-label" for="l0">Jam Selesai<span style="color: red">*</span></label>
        </div>
        <div class="col-md-4">
            <label class="input-group">
                <%= f.select :end_invitation_hour, Weeding::HOURS, {}, {'data-placeholder': '--Pilih Jam Selesai Meeting--', class: 'form-control selectpicker', 'data-live-search': 'true'} %>
                <span class="input-group-addon">
                    <i class="icmn-clock"></i>
                </span>
            </label>                                
        </div>
    </div>    

    <div class="form-group row">
        <div class="col-md-12">
            <label class="form-control-label" style="color: red">*required</label>
        </div>
    </div>
    <div class="form-group row">
        <div class="col-md-12"></div>
    </div>
    <!-- skip: reset_password_token, reset_password_sent_at, remember_created_at -->


    <% if params[:action] == "new" || params[:action] == "create" %>
        <%= f.hidden_field :created_by, :value => current_user.id %>   
    <% else %>
        <%= f.hidden_field :updated_by, :value => current_user.id %>
    <% end %>

    <button type="submit" class="btn btn-sm btn-primary">
        Submit
    </button>
    <% end %>
    
<%= content_for :css do %>

<% end %>

<%= content_for :js do %>
    
<% end %>  

app/views/admin/invited_guests/edit.html.erb
<div class="wrap-content container" id="container">
<!-- start: PAGE TITLE -->
<section id="page-title">
  <div class="row">
    <div class="col-sm-8">
      <h1 class="mainTitle">Form Ubah User Group</h1>
    </div>
    <ol class="breadcrumb">
      <li>
        <span>User Group Forms</span>
      </li>
      <li class="active">
        <span>Form User Group</span>
      </li>
    </ol>
  </div>
</section>
<!-- end: PAGE TITLE -->
<!-- start: BASIC EXAMPLE -->
<div class="container-fluid container-fullw bg-white">
  <div class="row">
    <div class="col-md-12">
      <div class="row">
        <div class="col-lg-12 col-md-12">
          <div class="panel panel-white">
            <div class="panel-heading">
              <h5 class="panel-title">Form User Group</h5>
            </div>
            <div class="panel-body">
            <%= render "form" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12 space20">
      <a href="/admin/user_groups" class="btn btn-sm btn-info">
        Kembali <i class="fa fa-reply"></i>
      </a>
    </div>
  </div>
</div>
<!-- end: BASIC EXAMPLE -->
</div>

app/views/admin/invited_guests/index.html.erb
<section class="page-content">
<div class="page-content-inner">

    <!--  -->
    <section class="panel">
        <div class="panel-heading">
            <h3>
                Daftar Daftar Undangan
            </h3>
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-lg-12">
                      <%= link_to '<i class="icon-plus icon-white"></i>Create New'.html_safe, new_admin_invited_guest_path, class: "btn btn-sm btn-info" %>                    
                    <div class="col-xs-12">&nbsp;</div>
                    <br/>
                    <div class="margin-bottom-50">                        
                        <table class="table table-hover nowrap" id="example1" width="100%">
                          <thead>
                            <tr>
                              <th>Nama</th>
                              <th>Total Tamu</th>
                              <th>Kehadiran</th>
                              <th>Aksi</th>
                            </tr>
                          </thead>
                          <tbody>
                            <% @invited_guests.each do |invited_guest| %>
                              <tr>
                                <td><%= link_to invited_guest.name,admin_invited_guest_path(invited_guest) %></td>
                                <td><%= invited_guest.total_guest %></td>
                                <td><%= invited_guest.attend %></td>
                                <td>
                                  <%= link_to edit_admin_invited_guest_path(invited_guest) do %>
                                    <i class="fa fa-edit"></i>
                                  <% end %>
                                  <%= link_to admin_invited_guest_path(invited_guest), method: :delete, data: {confirm: "are you sure?"} do %>
                                    <i class="fa fa-trash"></i>
                                  <% end %>
                                </td>
                              </tr>
                            <% end %>
                          </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- End  -->

</div>
</section>

app/views/admin/invited_guests/new.html.erb
<div class="wrap-content container" id="container">
<!-- start: PAGE TITLE -->
<section id="page-title">
    <div class="row">
        <div class="col-sm-8">
            <span class="mainDeskripsi">Form untuk menambah data Daftar Undangan yang baru</span>
        </div>
        <ol class="breadcrumb">
            <li>
                <span>Daftar Undangan Form</span>
            </li>
            <li class="active">
                <span>Form Daftar Undangan</span>
            </li>
        </ol>
    </div>
</section>
<!-- end: PAGE TITLE -->
<!-- start: BASIC EXAMPLE -->
<div class="container-fluid container-fullw bg-white">
    <div class="row">
        <div class="col-md-12">
            <div class="row">
                <div class="col-lg-12 col-md-12">
                    <div class="panel panel-white">
                        <div class="panel-heading">
                            <h5 class="panel-title">Form Daftar Undangan</h5>
                        </div>
                        <div class="panel-body">
                            <%= render "form" %>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12 space20">
        <a href="/admin/user_groups" class="btn btn-sm btn-info">
            Kembali <i class="fa fa-reply"></i>
        </a>
        </div>
      </div>
</div>
<!-- end: BASIC EXAMPLE -->
</div>

app/views/admin/invited_guests/show.html.erb
<div class="row">
    <div class="col-lg-12">
        <div class="wrapper wrapper-content animated fadeInUp">
            <div class="ibox">
                <div class="ibox-content">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="m-b-md">
                                <a href="/user_groups/<%= params[:id] %>/edit" class="btn btn-white btn-xs float-right">
                                  Edit Data User Group <i class="fa fa-edit"></i>
                                </a>
                                <a href="/user_groups" class="btn btn-white btn-xs float-right">
                                  Back <i class="fa fa-back"></i>
                                </a>
                                <h2>Data User Group</h2>
                            </div>

                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-12">
                            <!-- Informasi Master Institution -->
                            <h4 class="mb-0 m-t-md text-navy text-uppercase">Informasi User Group</h4>
                            <hr class="mb-1 m-t-xs">
                            <dl class="row mb-0">
                                <div class="col-sm-4 text-sm-right"><dt>Name:</dt> </div>
                                <div class="col-sm-8 text-sm-left"><dd class="mb-1"><%= @user_group.name %></dd></div>
                            </dl>
                            <dl class="row mb-0">
                                <div class="col-sm-4 text-sm-right"><dt>Description:</dt> </div>
                                <div class="col-sm-8 text-sm-left"><dd class="mb-1"><%= @user_group.description %></dd></div>
                            </dl>
                        </div>                        
                    </div>
                    <div class="col-xs-12">&nbsp;</div>                    
                </div>
            </div>
        </div>
    </div>
</div>