config/routes.rb
Rails.application.routes.draw do
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'homes#index'
  get 'admins' => 'admins#index', :as => 'admin_root'
  get 'undangan/:id' => 'bridegrooms#index'
  devise_for :users, :path => '', :path_names => { :sign_in => "login", :sign_out => "logout", :sign_up => "register" }
  namespace :admin do    
    resources :users    
    resources :user_groups
    resources :brides    
    resources :grooms
    resources :invited_guests    
    resources :weedings    
    resources :weeding_photos    
  end

end

app/models/action_model.rb
class ActionModel < ApplicationRecord
    belongs_to :controller_model
	has_and_belongs_to_many :user_groups, join_table: "action_models_user_groups"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bride.rb
class Bride < ApplicationRecord
    belongs_to :user, required: false, dependent: :destroy
    has_one_attached :image
end

app/models/controller_model.rb
class ControllerModel < ApplicationRecord
    has_many :action_models
end

app/models/groom.rb
class Groom < ApplicationRecord
    belongs_to :user, required: false, dependent: :destroy
    has_one_attached :image
end

app/models/invited_guest.rb
class InvitedGuest < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :user_group

  extend FriendlyId
  friendly_id :name, use: :slugged
  
  def has_priviledge(controller_name, action_name)
    @not_authorized = true

    self.user_group.action_models.each do |action_model|
      if (action_model.controller_model.path == controller_name && action_model.path == action_name)
        @not_authorized = false
      end

      break if ! @not_authorized
    end

    if (! @not_authorized || self.user_group.super == 1)
      true
    else
      false 
    end
  end
end

app/models/user_group.rb
class UserGroup < ApplicationRecord
    has_and_belongs_to_many :action_models, join_table: "action_models_user_groups"
end

app/models/weeding.rb
class Weeding < ApplicationRecord
    
    HOURS_DETAIL = [["--Pilih Jam--", ""],["00:00", 0] ,["01:00", 1], ["02:00", 2], ["03:00", 3], ["04:00", 4], ["05:00", 5], ["06:00", 6], ["07:00", 7], ["08:00", 8], ["09:00", 9], ["10:00", 10], 
                                    ["11:00", 11], ["12:00", 12], ["13:00", 13], ["14:00", 14], ["15:00", 15], ["16:00", 16], ["17:00", 17], ["18:00", 18],
                                    ["20:00", 20], ["21:00", 21], ["22:00", 22], ["23:00", 23]]
                                    
    HOURS = [["--Pilih Jam--", ""], ["07:00", 7], ["08:00", 8], ["09:00", 9], ["10:00", 10], 
            ["11:00", 11], ["12:00", 12], ["13:00", 13], ["14:00", 14], ["15:00", 15], ["16:00", 16], 
            ["17:00", 17], ["18:00", 18], ["19:00", 19], ["20:00", 20], ["21:00", 21], ["22:00", 22], ["23:00", 23]]

    has_many :weeding_photos
end

app/models/weeding_photo.rb
class WeedingPhoto < ApplicationRecord
    has_one_attached :image
end

app/controllers/admin/user_groups_controller.rb
class Admin::UserGroupsController < ApplicationController
  before_action :authenticate_user!
  before_action :authorize_user
  before_action :set_user_group, only: [:show, :edit, :update, :destroy]
  layout "admin"
    
  def index
    @user_groups = UserGroup.order("name DESC")
  end
  
  def new
    @user_group = UserGroup.new
   
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @user_group }
    end
  end
  
  def show 

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user_group }
    end
  end
  
  def create
    @user_group = UserGroup.new(user_group_params)
    
    respond_to do |format|
      if @user_group.save
        
        format.html { redirect_to(:controller => 'user_groups') }
        format.xml  { render :xml => @user_group, :status => :created, :user_group => @user_group }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @user_group.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  def edit 
  end
  
  def update 

    respond_to do |format|
      if @user_group.update_attributes(user_group_params)
        
        format.html { redirect_to(:controller => 'user_groups') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @user_group.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  def destroy
    @user_group.destroy

    respond_to do |format|
      format.html { redirect_to(:controller => 'user_groups') }
      format.xml  { head :ok }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user_group
    @user_group = UserGroup.find(params[:id])
  end


  def user_group_params
    params.require(:user_group).permit(:name, :super, :description, :created_by, :updated_by, action_model_ids: [])
  end
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
    before_action :authenticate_user!
    layout "admin"
    
	def index
		
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
	protect_from_forgery with: :null_session

	layout :layout_by_resource
	
	before_action :controller_model


	  def controller_model
	    @months = ["", "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Jul", "Agustus", "September", "Oktober", "November", "Desember"]
	    @days = ["Minggu", "Senin", "Selasa", "Rabu", "Kamis", "Jum'at", "Sabtu"]
	    Time.zone = "Jakarta"
	  end
	  
	  def layout_by_resource
		if devise_controller?
		  if resource_name == :user
			"login"
		  end
		else
		  "application"
		end
	   end
	  
	  def after_sign_in_path_for(resource_or_scope)
		  if resource_or_scope.is_a?(Admin)
		  admin_root_path    
		else
		  super
		end
	  end
	  
	  def after_sign_out_path_for(resource_or_scope)
		if resource_or_scope.to_s == "admin"
		  new_admin_session_path
		else
		  root_path
		end
	  end

	  def authorize_user
	    if current_user.has_priviledge(params[:controller], params[:action])
	      true
	    else
	      redirect_to admin_root_path, notice: "You're not authorized to access the page"
	    end
	  end
end

app/controllers/bridegrooms_controller.rb
class BridegroomsController < ApplicationController
    layout "application"

    def index

		@user = User.friendly.find(params[:id])
		@groom = Groom.find_by_user_id(@user.id)
		@bride = Bride.find_by_user_id(@user.id)		
		@weeding = Weeding.find_by_user_id(@user.id)
		# render json: @weeding
	end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
    # before_action :authenticate_user!, only: [:index]
	layout "application_default"
	
	def index
		@months = ["Januari", "Februari", "Maret", "April", "Mei", "Juni", "Jul", "Agustus", "September", "Oktober", "November", "Desember"];		
	end	

end

app/helpers/admin/brides_helper.rb
module Admin::BridesHelper
end

app/helpers/admin/grooms_helper.rb
module Admin::GroomsHelper
end

app/helpers/admin/user_groups_helper.rb
module Admin::UserGroupsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bridegrooms_helper.rb
module BridegroomsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/user_groups/_form.html.erb
<%= form_for([:admin, @user_group], html: {class: "form-horizontal"}) do |f| %>
<% if @user_group.errors.any? %>
    <div id="error_explanation">
    <h2><%= pluralize(@user_group.errors.count, "error") %> prohibited this user from being saved:</h2>
    <ul>
    <% @user_group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
    <% end %>
    </ul>
    </div>
<% end %>

    <div class="form-group row">
        <div class="col-md-3">
            <label class="form-control-label" for="l0">Nama<span style="color: red">*</span></label>
        </div>
        <div class="col-md-9">
            <%= f.text_field :name, class: "form-control", :required => true %>
        </div>
    </div> 
    <div class="form-group row">
        <div class="col-md-3">
            <label class="form-control-label" for="l0">Super Admin<span style="color: red">*</span></label>
        </div>
        <div class="col-md-9">
            <label class="radio-inline">
                <input type="radio" name="user_group[super]" id="user_group_super_1" value="1" <%= @user_group.super == 1 ? "checked" : "" %>> Yes </label>
                <label class="radio-inline">
                <input type="radio" name="user_group[super]" id="user_group_super_0" value="0" <%= @user_group.super == 0 ? "checked" : "" %>> No </label>
        </div>
    </div>  
    <div class="form-group row">
        <div class="col-md-3">
            <label class="form-control-label" for="l0">Hak Akses<span style="color: red">*</span></label>
        </div>
        <div class="col-md-9">
            <% current_controller = "" %>
            <% ActionModel.all.each do |action_model| %>
                <% if action_model.controller_model.name != current_controller %>
                    <% current_controller = action_model.controller_model.name %>
                    <div style="float:left; width:90%; margin-top:20px;margin-bottom:5px;font-family:Arial">
                        <label for="">
                            <b><%= current_controller %></b>
                        </label>
                    </div>
                <% end %>
                <div style="float:left; width:40%;">
                    <%= check_box_tag "user_group[action_model_ids][]", action_model.id, @user_group.action_models.include?(action_model),{class: "priviledges-checkbox children-#{action_model.controller_model.id}"} %>
                    <%= action_model.name %>
                </div>
            <% end %>
        </div>
    </div> 
    <div class="form-group row">
        <div class="col-md-12">
            <label class="form-control-label" style="color: red">*required</label>
        </div>
    </div>
    <div class="form-group row">
        <div class="col-md-12"></div>
    </div>
    <!-- skip: reset_password_token, reset_password_sent_at, remember_created_at -->


    <% if params[:action] == "new" || params[:action] == "create" %>
        <%= f.hidden_field :created_by, :value => current_user.id %>   
    <% else %>
        <%= f.hidden_field :updated_by, :value => current_user.id %>
    <% end %>

    <button type="submit" class="btn btn-sm btn-primary">
        Submit
    </button>
    <% end %>
    
<%= content_for :css do %>

<% end %>

<%= content_for :js do %>
    
<% end %>  

app/views/admin/user_groups/edit.html.erb
<div class="wrap-content container" id="container">
<!-- start: PAGE TITLE -->
<section id="page-title">
  <div class="row">
    <div class="col-sm-8">
      <h1 class="mainTitle">Form Ubah User Group</h1>
    </div>
    <ol class="breadcrumb">
      <li>
        <span>User Group Forms</span>
      </li>
      <li class="active">
        <span>Form User Group</span>
      </li>
    </ol>
  </div>
</section>
<!-- end: PAGE TITLE -->
<!-- start: BASIC EXAMPLE -->
<div class="container-fluid container-fullw bg-white">
  <div class="row">
    <div class="col-md-12">
      <div class="row">
        <div class="col-lg-12 col-md-12">
          <div class="panel panel-white">
            <div class="panel-heading">
              <h5 class="panel-title">Form User Group</h5>
            </div>
            <div class="panel-body">
            <%= render "form" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12 space20">
      <a href="/admin/user_groups" class="btn btn-sm btn-info">
        Kembali <i class="fa fa-reply"></i>
      </a>
    </div>
  </div>
</div>
<!-- end: BASIC EXAMPLE -->
</div>

app/views/admin/user_groups/index.html.erb
<section class="page-content">
<div class="page-content-inner">

    <!--  -->
    <section class="panel">
        <div class="panel-heading">
            <h3>
                Daftar User Groups
            </h3>
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-lg-12">
                      <%= link_to '<i class="icon-plus icon-white"></i>Create New'.html_safe, new_admin_user_group_path, class: "btn btn-sm btn-info" %>                    
                    <div class="col-xs-12">&nbsp;</div>
                    <br/>
                    <div class="margin-bottom-50">                        
                        <table class="table table-hover nowrap" id="example1" width="100%">
                          <thead>
                            <tr>
                              <th>Nama</th>
                              <th>Description</th>
                              <th>Aksi</th>
                            </tr>
                          </thead>
                          <tbody>
                            <% @user_groups.each do |user_group| %>
                              <tr>
                                <td><%= link_to user_group.name,admin_user_group_path(user_group) %></td>
                                <td><%= user_group.description %></td>
                                <td>
                                  <%= link_to edit_admin_user_group_path(user_group) do %>
                                    <i class="fa fa-edit"></i>
                                  <% end %>
                                  <%= link_to admin_user_group_path(user_group), method: :delete, data: {confirm: "are you sure?"} do %>
                                    <i class="fa fa-trash"></i>
                                  <% end %>
                                </td>
                              </tr>
                            <% end %>
                          </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- End  -->

</div>
</section>

app/views/admin/user_groups/new.html.erb
<div class="wrap-content container" id="container">
<!-- start: PAGE TITLE -->
<section id="page-title">
    <div class="row">
        <div class="col-sm-8">
            <span class="mainDeskripsi">Form untuk menambah data User Group yang baru</span>
        </div>
        <ol class="breadcrumb">
            <li>
                <span>User Group Form</span>
            </li>
            <li class="active">
                <span>Form User Group</span>
            </li>
        </ol>
    </div>
</section>
<!-- end: PAGE TITLE -->
<!-- start: BASIC EXAMPLE -->
<div class="container-fluid container-fullw bg-white">
    <div class="row">
        <div class="col-md-12">
            <div class="row">
                <div class="col-lg-12 col-md-12">
                    <div class="panel panel-white">
                        <div class="panel-heading">
                            <h5 class="panel-title">Form User Group</h5>
                        </div>
                        <div class="panel-body">
                            <%= render "form" %>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12 space20">
        <a href="/admin/user_groups" class="btn btn-sm btn-info">
            Kembali <i class="fa fa-reply"></i>
        </a>
        </div>
      </div>
</div>
<!-- end: BASIC EXAMPLE -->
</div>

app/views/admin/user_groups/show.html.erb
<div class="row">
    <div class="col-lg-12">
        <div class="wrapper wrapper-content animated fadeInUp">
            <div class="ibox">
                <div class="ibox-content">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="m-b-md">
                                <a href="/user_groups/<%= params[:id] %>/edit" class="btn btn-white btn-xs float-right">
                                  Edit Data User Group <i class="fa fa-edit"></i>
                                </a>
                                <a href="/user_groups" class="btn btn-white btn-xs float-right">
                                  Back <i class="fa fa-back"></i>
                                </a>
                                <h2>Data User Group</h2>
                            </div>

                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-12">
                            <!-- Informasi Master Institution -->
                            <h4 class="mb-0 m-t-md text-navy text-uppercase">Informasi User Group</h4>
                            <hr class="mb-1 m-t-xs">
                            <dl class="row mb-0">
                                <div class="col-sm-4 text-sm-right"><dt>Name:</dt> </div>
                                <div class="col-sm-8 text-sm-left"><dd class="mb-1"><%= @user_group.name %></dd></div>
                            </dl>
                            <dl class="row mb-0">
                                <div class="col-sm-4 text-sm-right"><dt>Description:</dt> </div>
                                <div class="col-sm-8 text-sm-left"><dd class="mb-1"><%= @user_group.description %></dd></div>
                            </dl>
                        </div>                        
                    </div>
                    <div class="col-xs-12">&nbsp;</div>                    
                </div>
            </div>
        </div>
    </div>
</div>