config/routes.rb
Rails.application.routes.draw do
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'homes#index'
  get 'admins' => 'admins#index', :as => 'admin_root'
  get 'undangan/:id' => 'bridegrooms#index'
  devise_for :users, :path => '', :path_names => { :sign_in => "login", :sign_out => "logout", :sign_up => "register" }
  namespace :admin do    
    resources :users    
    resources :user_groups
    resources :brides    
    resources :grooms
    resources :invited_guests    
    resources :weedings    
    resources :weeding_photos    
  end

end

app/models/action_model.rb
class ActionModel < ApplicationRecord
    belongs_to :controller_model
	has_and_belongs_to_many :user_groups, join_table: "action_models_user_groups"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bride.rb
class Bride < ApplicationRecord
    belongs_to :user, required: false, dependent: :destroy
    has_one_attached :image
end

app/models/controller_model.rb
class ControllerModel < ApplicationRecord
    has_many :action_models
end

app/models/groom.rb
class Groom < ApplicationRecord
    belongs_to :user, required: false, dependent: :destroy
    has_one_attached :image
end

app/models/invited_guest.rb
class InvitedGuest < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :user_group

  extend FriendlyId
  friendly_id :name, use: :slugged
  
  def has_priviledge(controller_name, action_name)
    @not_authorized = true

    self.user_group.action_models.each do |action_model|
      if (action_model.controller_model.path == controller_name && action_model.path == action_name)
        @not_authorized = false
      end

      break if ! @not_authorized
    end

    if (! @not_authorized || self.user_group.super == 1)
      true
    else
      false 
    end
  end
end

app/models/user_group.rb
class UserGroup < ApplicationRecord
    has_and_belongs_to_many :action_models, join_table: "action_models_user_groups"
end

app/models/weeding.rb
class Weeding < ApplicationRecord
    
    HOURS_DETAIL = [["--Pilih Jam--", ""],["00:00", 0] ,["01:00", 1], ["02:00", 2], ["03:00", 3], ["04:00", 4], ["05:00", 5], ["06:00", 6], ["07:00", 7], ["08:00", 8], ["09:00", 9], ["10:00", 10], 
                                    ["11:00", 11], ["12:00", 12], ["13:00", 13], ["14:00", 14], ["15:00", 15], ["16:00", 16], ["17:00", 17], ["18:00", 18],
                                    ["20:00", 20], ["21:00", 21], ["22:00", 22], ["23:00", 23]]
                                    
    HOURS = [["--Pilih Jam--", ""], ["07:00", 7], ["08:00", 8], ["09:00", 9], ["10:00", 10], 
            ["11:00", 11], ["12:00", 12], ["13:00", 13], ["14:00", 14], ["15:00", 15], ["16:00", 16], 
            ["17:00", 17], ["18:00", 18], ["19:00", 19], ["20:00", 20], ["21:00", 21], ["22:00", 22], ["23:00", 23]]

    has_many :weeding_photos
end

app/models/weeding_photo.rb
class WeedingPhoto < ApplicationRecord
    has_one_attached :image
end

app/controllers/admin/weedings_controller.rb
class Admin::WeedingsController < ApplicationController
    before_action :authenticate_user!
    #before_action :authorize_user
    before_action :set_weeding, only: [:show, :edit, :update, :destroy]
    layout "admin"

    def index
        @weedings = Weeding.order("name DESC")
    end

    def new
        @weeding = Weeding.new

        respond_to do |format|
            format.html # new.html.erb
            format.xml  { render :xml => @weeding }
        end
    end

    def show 

        respond_to do |format|
            format.html # show.html.erb
            format.xml  { render :xml => @weeding }
        end
    end

    def create
        @weeding = Weeding.new(weeding_params)

        respond_to do |format|
            if @weeding.save
            
                format.html { redirect_to(:controller => 'weedings') }
                format.xml  { render :xml => @weeding, :status => :created, :weeding => @weeding }
            else
                format.html { render :action => "new" }
                format.xml  { render :xml => @weeding.errors, :status => :unprocessable_entity }
            end
        end
    end

    def edit 
    end

    def update 

        respond_to do |format|
            if @weeding.update_attributes(weeding_params)            
                format.html { redirect_to admin_grooms_path(user_id: current_user.id) , :notice => 'Data pengantin pria telah di buat.' }
                format.xml  { head :ok }
            else
                format.html { render :action => "edit" }
                format.xml  { render :xml => @weeding.errors, :status => :unprocessable_entity }
            end
        end
    end

    def destroy
        @weeding.destroy

        respond_to do |format|
            format.html { redirect_to(:controller => 'weedings') }
            format.xml  { head :ok }
        end
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_weeding
        @weeding = Weeding.find(params[:id])
    end


    def weeding_params
        params.require(:weeding).permit(:bride_id, :groom_id, :location_id, :start_date, :end_date, :start_time, :end_time, :number_guest)
    end
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
    before_action :authenticate_user!
    layout "admin"
    
	def index
		
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
	protect_from_forgery with: :null_session

	layout :layout_by_resource
	
	before_action :controller_model


	  def controller_model
	    @months = ["", "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Jul", "Agustus", "September", "Oktober", "November", "Desember"]
	    @days = ["Minggu", "Senin", "Selasa", "Rabu", "Kamis", "Jum'at", "Sabtu"]
	    Time.zone = "Jakarta"
	  end
	  
	  def layout_by_resource
		if devise_controller?
		  if resource_name == :user
			"login"
		  end
		else
		  "application"
		end
	   end
	  
	  def after_sign_in_path_for(resource_or_scope)
		  if resource_or_scope.is_a?(Admin)
		  admin_root_path    
		else
		  super
		end
	  end
	  
	  def after_sign_out_path_for(resource_or_scope)
		if resource_or_scope.to_s == "admin"
		  new_admin_session_path
		else
		  root_path
		end
	  end

	  def authorize_user
	    if current_user.has_priviledge(params[:controller], params[:action])
	      true
	    else
	      redirect_to admin_root_path, notice: "You're not authorized to access the page"
	    end
	  end
end

app/controllers/bridegrooms_controller.rb
class BridegroomsController < ApplicationController
    layout "application"

    def index

		@user = User.friendly.find(params[:id])
		@groom = Groom.find_by_user_id(@user.id)
		@bride = Bride.find_by_user_id(@user.id)		
		@weeding = Weeding.find_by_user_id(@user.id)
		# render json: @weeding
	end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
    # before_action :authenticate_user!, only: [:index]
	layout "application_default"
	
	def index
		@months = ["Januari", "Februari", "Maret", "April", "Mei", "Juni", "Jul", "Agustus", "September", "Oktober", "November", "Desember"];		
	end	

end

app/helpers/admin/brides_helper.rb
module Admin::BridesHelper
end

app/helpers/admin/grooms_helper.rb
module Admin::GroomsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/admin/weedings_helper.rb
module Admin::WeedingsHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bridegrooms_helper.rb
module BridegroomsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/weedings/_form.html.erb
<%= form_for([:admin, @weeding], html: {class: "form-horizontal"}) do |f| %>
    <% if @weeding.errors.any? %>
        <div id="error_explanation">
        <h2><%= pluralize(@weeding.errors.count, "error") %> prohibited this user from being saved:</h2>
        <ul>
        <% @weeding.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
        </ul>
        </div>
    <% end %>
    
    <div class="form-group row">
        <div class="col-md-2">
            <label class="form-control-label" for="l0">Tanggal Acara<span style="color: red">*</span></label>
        </div>
        <div class="col-md-10">
            <div class="form-group">
                <label class="input-group datepicker-only-init">
                    <%= f.text_field :start_date, class: "form-control", :required => true%>                    
                    <span class="input-group-addon">
                        <i class="icmn-calendar"></i>
                    </span>
                </label>
            </div>
        </div>
    </div>    

    <div class="form-group row">
        <div class="col-md-2">
            <label class="form-control-label" for="l0">Jam Mulai<span style="color: red">*</span></label>
        </div>
        <div class="col-md-4">
            <label class="input-group">
                <%= f.select :start_time, Weeding::HOURS, {}, {'data-placeholder': '--Pilih Jam Selesai Meeting--', class: 'form-control selectpicker', 'data-live-search': 'true'} %>
                <span class="input-group-addon">
                    <i class="icmn-clock"></i>
                </span>

                <%= f.hidden_field :end_time, id: "select-end-time" %>
            </label>                                
        </div>
        <div class="col-md-2">
            <label class="form-control-label" for="l0">Jam Selesai<span style="color: red">*</span></label>
        </div>
        <div class="col-md-4">
            <label class="input-group">
                <%= f.select :end_time, Weeding::HOURS, {}, {'data-placeholder': '--Pilih Jam Selesai Meeting--', class: 'form-control selectpicker', 'data-live-search': 'true'} %>
                <span class="input-group-addon">
                    <i class="icmn-clock"></i>
                </span>
            </label>                                
        </div>
    </div> 

    <div class="form-group row">
        <div class="col-md-2">
            <label class="form-control-label" for="l0">Jumlah Tamu<span style="color: red">*</span></label>
        </div>
        <div class="col-md-10">
            <%= f.number_field :number_guest, class: "form-control", :required => true %>
        </div>
    </div> 
   
    <div class="form-group row">
        <div class="col-md-12">
            <label class="form-control-label" style="color: red">*required</label>
        </div>
    </div>
    <div class="form-group row">
        <div class="col-md-12"></div>
    </div>
    <!-- skip: reset_password_token, reset_password_sent_at, remember_created_at -->

    <% if params[:action] == "new" || params[:action] == "create" %>
        <%= f.hidden_field :created_by, :value => current_user.id %>   
    <% else %>
        <%= f.hidden_field :updated_by, :value => current_user.id %>
    <% end %>

    <button type="submit" class="btn btn-sm btn-primary">
        Submit
    </button>
<% end %>
    
<%= content_for :css do %>

<% end %>

<%= content_for :js do %>
    <script>    
      $(document).ready(function() {          
          $('.select2').select2();
          $('.datepicker-only-init').datetimepicker({
            widgetPositioning: {
                horizontal: 'left'
            },
            icons: {
                time: "fa fa-clock-o",
                date: "fa fa-calendar",
                up: "fa fa-arrow-up",
                down: "fa fa-arrow-down"
            },
            format: 'LL'
        });
      });
  </script>
<% end %>  

app/views/admin/weedings/edit.html.erb
<div class="wrap-content container" id="container">
<!-- start: PAGE TITLE -->
<section id="page-title">
  <div class="row">
    <div class="col-sm-8">
      <h1 class="mainTitle">Form Informasi Acara</h1>
    </div>
    <ol class="breadcrumb">
      <li>
        <span>Informasi Acara</span>
      </li>
      <li class="active">
        <span>Form Edit</span>
      </li>
    </ol>
  </div>
</section>
<!-- end: PAGE TITLE -->
<!-- start: BASIC EXAMPLE -->
<div class="container-fluid container-fullw bg-white">
  <div class="row">
    <div class="col-md-12">
      <div class="row">
        <div class="col-lg-12 col-md-12">
          <div class="panel panel-white">
            <div class="panel-heading">
              <h5 class="panel-title">Form Informasi Acara</h5>
            </div>
            <div class="panel-body">
            <%= render "form" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12 space20">
      <a href="/admin/grooms?user_id=<%= current_user.id %>" class="btn btn-sm btn-info">
        Kembali <i class="fa fa-reply"></i>
      </a>
    </div>
  </div>
</div>
<!-- end: BASIC EXAMPLE -->
</div>

app/views/admin/weedings/index.html.erb
<section class="page-content">
<div class="page-content-inner">

    <!--  -->
    <section class="panel">
        <div class="panel-heading">
            <h3>
                Daftar User
            </h3>
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-lg-12">
                      <%= link_to '<i class="icon-plus icon-white"></i>Create New'.html_safe, new_admin_user_path, class: "btn btn-sm btn-info" %>                    
                    <div class="col-xs-12">&nbsp;</div>
                    <br/>
                    <div class="margin-bottom-50">                        
                        <table class="table table-hover nowrap" id="example1" width="100%">
                          <thead>
                            <tr>
                              <th>Nama</th>
                              <th>Email</th>
                              <th>User Group</th>
                              <th>Aksi</th>
                            </tr>
                          </thead>
                          <tbody>
                            <% @users.each do |user| %>
                              <tr>
                                <td><%= link_to user.name,admin_user_path(user) %></td>
                                <td><%= user.email %></td>
                                <td><%= user.user_group ? user.user_group.name : '' %></td>
                                <td>
                                  <%= link_to edit_admin_user_path(user) do %>
                                    <i class="fa fa-edit"></i>
                                  <% end %>
                                  <%= link_to admin_user_path(user), method: :delete, data: {confirm: "are you sure?"} do %>
                                    <i class="fa fa-trash"></i>
                                  <% end %>
                                </td>
                              </tr>
                            <% end %>
                          </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- End  -->

</div>
</section>

app/views/admin/weedings/new.html.erb
<div class="wrap-content container" id="container">
<!-- start: PAGE TITLE -->
<section id="page-title">
    <div class="row">
        <div class="col-sm-8">
            <span class="mainDeskripsi">Form untuk menambah data User yang baru</span>
        </div>
        <ol class="breadcrumb">
            <li>
                <span>User Form</span>
            </li>
            <li class="active">
                <span>Form User</span>
            </li>
        </ol>
    </div>
</section>
<!-- end: PAGE TITLE -->
<!-- start: BASIC EXAMPLE -->
<div class="container-fluid container-fullw bg-white">
    <div class="row">
        <div class="col-md-12">
            <div class="row">
                <div class="col-lg-12 col-md-12">
                    <div class="panel panel-white">
                        <div class="panel-heading">
                            <h5 class="panel-title">Form User</h5>
                        </div>
                        <div class="panel-body">
                            <%= render "form" %>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12 space20">
        <a href="/admin/users" class="btn btn-sm btn-info">
            Kembali <i class="fa fa-reply"></i>
        </a>
        </div>
      </div>
</div>
<!-- end: BASIC EXAMPLE -->
</div>

app/views/admin/weedings/show.html.erb
<div class="wrap-content container" id="container">
<!-- start: PAGE TITLE -->
<section id="page-title">
  <div class="row">
    <div class="col-sm-8">
      <h1 class="mainTitle">User Data Detail</h1>
      <span class="mainDeskripsi">Halaman untuk melihat detail User</span>
    </div>
    <ol class="breadcrumb">
      <li>
        <span>User View</span>
      </li>
      <li class="active">
        <span>View User</span>
      </li>
    </ol>
  </div>
</section>
<!-- end: PAGE TITLE -->
<!-- start: BASIC EXAMPLE -->
    <div class="container-fluid container-fullw bg-white">
      <div class="row">
        <div class="col-md-12">
          <div class="row">
            <div class="col-lg-12 col-md-12">
              <div class="panel panel-white">
                <div class="panel-heading">
                  <h5 class="panel-title">Detail User <%= @user.name %></h5>
                </div>
                <div class="panel-body">
                  <table class="table">
                    <tbody>                                      
                      <tr>
                        <td>Email</td>
                        <td><%= @user.email %></td>
                      </tr>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    <div class="row">
      <div class="col-md-12 space20">
        <a href="/admin/users/<%= params[:id] %>/edit" class="btn btn-sm btn-warning">
          Ubah <i class="fa fa-edit"></i>
        </a>
        <a href="/admin/users" class="btn btn-sm btn-info">
          Kembali <i class="fa fa-reply"></i>
        </a>
      </div>
    </div>
  </div>
</div>
<!-- end: BASIC EXAMPLE -->

<!-- start: DYNAMIC TABLE -->
<%= content_for :css do %>
<!-- end: CSS REQUIRED FOR THIS PAGE ONLY -->
<% end %>

<%= content_for :js do %>
<!-- end: JavaScript Event Handlers for this page -->
<% end %>