config/routes.rb
Rails.application.routes.draw do
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'homes#index'
  get 'admins' => 'admins#index', :as => 'admin_root'
  get 'undangan/:id' => 'bridegrooms#index'
  devise_for :users, :path => '', :path_names => { :sign_in => "login", :sign_out => "logout", :sign_up => "register" }
  namespace :admin do    
    resources :users    
    resources :user_groups
    resources :brides    
    resources :grooms
    resources :invited_guests    
    resources :weedings    
    resources :weeding_photos    
  end

end

app/models/action_model.rb
class ActionModel < ApplicationRecord
    belongs_to :controller_model
	has_and_belongs_to_many :user_groups, join_table: "action_models_user_groups"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bride.rb
class Bride < ApplicationRecord
    belongs_to :user, required: false, dependent: :destroy
    has_one_attached :image
end

app/models/controller_model.rb
class ControllerModel < ApplicationRecord
    has_many :action_models
end

app/models/groom.rb
class Groom < ApplicationRecord
    belongs_to :user, required: false, dependent: :destroy
    has_one_attached :image
end

app/models/invited_guest.rb
class InvitedGuest < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :user_group

  extend FriendlyId
  friendly_id :name, use: :slugged
  
  def has_priviledge(controller_name, action_name)
    @not_authorized = true

    self.user_group.action_models.each do |action_model|
      if (action_model.controller_model.path == controller_name && action_model.path == action_name)
        @not_authorized = false
      end

      break if ! @not_authorized
    end

    if (! @not_authorized || self.user_group.super == 1)
      true
    else
      false 
    end
  end
end

app/models/user_group.rb
class UserGroup < ApplicationRecord
    has_and_belongs_to_many :action_models, join_table: "action_models_user_groups"
end

app/models/weeding.rb
class Weeding < ApplicationRecord
    
    HOURS_DETAIL = [["--Pilih Jam--", ""],["00:00", 0] ,["01:00", 1], ["02:00", 2], ["03:00", 3], ["04:00", 4], ["05:00", 5], ["06:00", 6], ["07:00", 7], ["08:00", 8], ["09:00", 9], ["10:00", 10], 
                                    ["11:00", 11], ["12:00", 12], ["13:00", 13], ["14:00", 14], ["15:00", 15], ["16:00", 16], ["17:00", 17], ["18:00", 18],
                                    ["20:00", 20], ["21:00", 21], ["22:00", 22], ["23:00", 23]]
                                    
    HOURS = [["--Pilih Jam--", ""], ["07:00", 7], ["08:00", 8], ["09:00", 9], ["10:00", 10], 
            ["11:00", 11], ["12:00", 12], ["13:00", 13], ["14:00", 14], ["15:00", 15], ["16:00", 16], 
            ["17:00", 17], ["18:00", 18], ["19:00", 19], ["20:00", 20], ["21:00", 21], ["22:00", 22], ["23:00", 23]]

    has_many :weeding_photos
end

app/models/weeding_photo.rb
class WeedingPhoto < ApplicationRecord
    has_one_attached :image
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
    before_action :authenticate_user!
    layout "admin"
    
	def index
		
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
	protect_from_forgery with: :null_session

	layout :layout_by_resource
	
	before_action :controller_model


	  def controller_model
	    @months = ["", "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Jul", "Agustus", "September", "Oktober", "November", "Desember"]
	    @days = ["Minggu", "Senin", "Selasa", "Rabu", "Kamis", "Jum'at", "Sabtu"]
	    Time.zone = "Jakarta"
	  end
	  
	  def layout_by_resource
		if devise_controller?
		  if resource_name == :user
			"login"
		  end
		else
		  "application"
		end
	   end
	  
	  def after_sign_in_path_for(resource_or_scope)
		  if resource_or_scope.is_a?(Admin)
		  admin_root_path    
		else
		  super
		end
	  end
	  
	  def after_sign_out_path_for(resource_or_scope)
		if resource_or_scope.to_s == "admin"
		  new_admin_session_path
		else
		  root_path
		end
	  end

	  def authorize_user
	    if current_user.has_priviledge(params[:controller], params[:action])
	      true
	    else
	      redirect_to admin_root_path, notice: "You're not authorized to access the page"
	    end
	  end
end

app/controllers/bridegrooms_controller.rb
class BridegroomsController < ApplicationController
    layout "application"

    def index

		@user = User.friendly.find(params[:id])
		@groom = Groom.find_by_user_id(@user.id)
		@bride = Bride.find_by_user_id(@user.id)		
		@weeding = Weeding.find_by_user_id(@user.id)
		# render json: @weeding
	end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
    # before_action :authenticate_user!, only: [:index]
	layout "application_default"
	
	def index
		@months = ["Januari", "Februari", "Maret", "April", "Mei", "Juni", "Jul", "Agustus", "September", "Oktober", "November", "Desember"];		
	end	

end

app/helpers/admin/brides_helper.rb
module Admin::BridesHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bridegrooms_helper.rb
module BridegroomsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admins/index.html.erb
<!-- Dashboard  -->
<div class="dashboard-container">
    <div class="widget widget-four background-transparent">
        <div class="row">
            <div class="col-xl-4 col-lg-6 col-sm-6 col-xs-12">
                <div class="step-block ">
                    <span class="step-digit">
                        <i class="icmn-user-plus2"><!-- --></i>
                    </span>
                    <div class="step-desc">
                        <span class="step-title">Total Undangan</span>
                        <p>
                            Total: <%= @transaction_count %>
                        </p>
                    </div>
                </div>
            </div>
            <div class="col-xl-4 col-lg-6 col-sm-6 col-xs-12">
                <div class="step-block">
                    <span class="step-digit">
                        <i class="icmn-user3"><!-- --></i>
                    </span>
                    <div class="step-desc">
                        <span class="step-title">Total Tamu Hadir</span>
                        <p>Total: <%= @transaction_month_count %></p>
                    </div>
                </div>
            </div>
            <div class="col-xl-4 col-lg-6 col-sm-6 col-xs-12">
                <div class="step-block">
                    <span class="step-digit">
                        <i class="icmn-user5"><!-- --></i>
                    </span>
                    <div class="step-desc">
                        <span class="step-title">Total Tamu Tidak Hadir</span>
                        <p>
                            Total: <%= @purchase_count %>
                        </p>
                    </div>
                </div>
            </div>
            <div class="col-xl-4 col-lg-6 col-sm-6 col-xs-12">
                <div class="step-block">
                    <span class="step-digit">
                        <i class="icmn-stats-dots"><!-- --></i>
                    </span>
                    <div class="step-desc">
                        <span class="step-title">Total Pembelian Bulan ini</span>
                        <p>                            
                            Total: <%= @purchase_month_count %>                            
                        </p>
                    </div>
                </div>
            </div>
            <!--  -->
            <div class="col-xl-4 col-lg-6 col-sm-6 col-xs-12">
                <div class="step-block ">
                    <span class="step-digit">
                        <i class="icmn-user-plus2"><!-- --></i>
                    </span>
                    <div class="step-desc">
                        <span class="step-title">Total Vendor</span>
                        <p>
                            Total: <%= @vendor %>
                        </p>
                    </div>
                </div>
            </div>
            <div class="col-xl-4 col-lg-6 col-sm-6 col-xs-12">
                <div class="step-block">
                    <span class="step-digit">
                        <i class="icmn-user3"><!-- --></i>
                    </span>
                    <div class="step-desc">
                        <span class="step-title">Total Client</span>
                        <p>
                            Total: <%= @client %>
                        </p>                        
                    </div>
                </div>
            </div>
            <div class="col-xl-4 col-lg-6 col-sm-6 col-xs-12">
                <div class="step-block">
                    <span class="step-digit">
                        <i class="icmn-hammer-wrench"><!-- --></i>
                    </span>
                    <div class="step-desc">
                        <span class="step-title">Total Jenis Service</span>
                        <p>
                            Total: <%= @service %>
                        </p>
                    </div>
                </div>
            </div>
            <div class="col-xl-4 col-lg-6 col-sm-6 col-xs-12">
                <div class="step-block">
                    <span class="step-digit">
                        <i class="icmn-cogs"><!-- --></i>
                    </span>
                    <div class="step-desc">
                        <span class="step-title">Total Jenis Sparepart</span>
                        <p>
                            Total: <%= @sparepart %>
                        </p>
                    </div>
                </div>
            </div>
            
        </div>
    </div>

    <section class="page-content">
<div class="page-content-inner">

    <!--  -->
    
    <!-- End  -->

</div>
</section>

</div>
<br><br><br>
<br><br><br>
<!-- Page Scripts -->
<script>
   
</script>

<!-- End Dashboard

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Kami Mengundan Dashboard</title>

    <link href="/backend/common/img/favicon.144x144.png" rel="apple-touch-icon" type="image/png" sizes="144x144">
    <link href="/backend/common/img/favicon.114x114.png" rel="apple-touch-icon" type="image/png" sizes="114x114">
    <link href="/backend/common/img/favicon.72x72.png" rel="apple-touch-icon" type="image/png" sizes="72x72">
    <link href="/backend/common/img/favicon.57x57.png" rel="apple-touch-icon" type="image/png">
    <link href="/backend/common/img/favicon.png" rel="icon" type="image/png">
    <link href="favicon.ico" rel="shortcut icon">

    <!-- HTML5 shim and Respond.js for < IE9 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- Vendors Styles -->
    <!-- v1.0.0 -->
    <link rel="stylesheet" type="text/css" href="/backend/vendors/bootstrap/dist/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="/backend/vendors/jscrollpane/style/jquery.jscrollpane.css">
    <link rel="stylesheet" type="text/css" href="/backend/vendors/ladda/dist/ladda-themeless.min.css">
    <link rel="stylesheet" type="text/css" href="/backend/vendors/select2/dist/css/select2.min.css">
    <link rel="stylesheet" type="text/css" href="/backend/vendors/eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.min.css">
    <link rel="stylesheet" type="text/css" href="/backend/vendors/fullcalendar/dist/fullcalendar.min.css">
    <link rel="stylesheet" type="text/css" href="/backend/vendors/cleanhtmlaudioplayer/src/player.css">
    <link rel="stylesheet" type="text/css" href="/backend/vendors/cleanhtmlvideoplayer/src/player.css">
    <link rel="stylesheet" type="text/css" href="/backend/vendors/bootstrap-sweetalert/dist/sweetalert.css">
    <link rel="stylesheet" type="text/css" href="/backend/vendors/summernote/dist/summernote.css">
    <link rel="stylesheet" type="text/css" href="/backend/vendors/owl.carousel/dist/assets/owl.carousel.min.css">
    <link rel="stylesheet" type="text/css" href="/backend/vendors/ionrangeslider/css/ion.rangeSlider.css">
    <link rel="stylesheet" type="text/css" href="/backend/vendors/datatables/media/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" type="text/css" href="/backend/vendors/c3/c3.min.css">
    <link rel="stylesheet" type="text/css" href="/backend/vendors/chartist/dist/chartist.min.css">
    <!-- v1.4.0 -->
    <link rel="stylesheet" type="text/css" href="/backend/vendors/nprogress/nprogress.css">
    <link rel="stylesheet" type="text/css" href="/backend/vendors/jquery-steps/demo/css/jquery.steps.css">
    <!-- v1.4.2 -->
    <link rel="stylesheet" type="text/css" href="/backend/vendors/bootstrap-select/dist/css/bootstrap-select.min.css">
    <!-- v1.7.0 -->
    <link rel="stylesheet" type="text/css" href="/backend/vendors/dropify/dist/css/dropify.min.css">

    <!-- Clean UI Styles -->
    <link rel="stylesheet" type="text/css" href="/backend/common/css/source/main.css">

    <!-- Vendors Scripts -->
    <!-- v1.0.0 -->
    <script src="/backend/vendors/jquery/jquery.min.js"></script>
    <script src="/backend/vendors/tether/dist/js/tether.min.js"></script>
    <script src="/backend/vendors/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="/backend/vendors/jquery-mousewheel/jquery.mousewheel.min.js"></script>
    <script src="/backend/vendors/jscrollpane/script/jquery.jscrollpane.min.js"></script>
    <script src="/backend/vendors/spin.js/spin.js"></script>
    <script src="/backend/vendors/ladda/dist/ladda.min.js"></script>
    <script src="/backend/vendors/select2/dist/js/select2.full.min.js"></script>
    <script src="/backend/vendors/html5-form-validation/dist/jquery.validation.min.js"></script>
    <script src="/backend/vendors/jquery-typeahead/dist/jquery.typeahead.min.js"></script>
    <script src="/backend/vendors/jquery-mask-plugin/dist/jquery.mask.min.js"></script>
    <script src="/backend/vendors/autosize/dist/autosize.min.js"></script>
    <script src="/backend/vendors/bootstrap-show-password/bootstrap-show-password.min.js"></script>
    <script src="/backend/vendors/moment/min/moment.min.js"></script>
    <script src="/backend/vendors/eonasdan-bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js"></script>
    <script src="/backend/vendors/fullcalendar/dist/fullcalendar.min.js"></script>
    <script src="/backend/vendors/cleanhtmlaudioplayer/src/jquery.cleanaudioplayer.js"></script>
    <script src="/backend/vendors/cleanhtmlvideoplayer/src/jquery.cleanvideoplayer.js"></script>
    <script src="/backend/vendors/bootstrap-sweetalert/dist/sweetalert.min.js"></script>
    <script src="/backend/vendors/remarkable-bootstrap-notify/dist/bootstrap-notify.min.js"></script>
    <script src="/backend/vendors/summernote/dist/summernote.min.js"></script>
    <script src="/backend/vendors/owl.carousel/dist/owl.carousel.min.js"></script>
    <script src="/backend/vendors/ionrangeslider/js/ion.rangeSlider.min.js"></script>
    <script src="/backend/vendors/nestable/jquery.nestable.js"></script>
    <script src="/backend/vendors/datatables/media/js/jquery.dataTables.min.js"></script>
    <script src="/backend/vendors/datatables/media/js/dataTables.bootstrap4.min.js"></script>
    <script src="/backend/vendors/datatables-fixedcolumns/js/dataTables.fixedColumns.js"></script>
    <script src="/backend/vendors/datatables-responsive/js/dataTables.responsive.js"></script>
    <script src="/backend/vendors/editable-table/mindmup-editabletable.js"></script>
    <script src="/backend/vendors/d3/d3.min.js"></script>
    <script src="/backend/vendors/c3/c3.min.js"></script>
    <script src="/backend/vendors/chartist/dist/chartist.min.js"></script>
    <script src="/backend/vendors/peity/jquery.peity.min.js"></script>
    <!-- v1.0.1 -->
    <script src="/backend/vendors/chartist-plugin-tooltip/dist/chartist-plugin-tooltip.min.js"></script>
    <!-- v1.1.1 -->
    <script src="/backend/vendors/gsap/src/minified/TweenMax.min.js"></script>
    <script src="/backend/vendors/hackertyper/hackertyper.js"></script>
    <script src="/backend/vendors/jquery-countTo/jquery.countTo.js"></script>
    <!-- v1.4.0 -->
    <script src="/backend/vendors/nprogress/nprogress.js"></script>
    <script src="/backend/vendors/jquery-steps/build/jquery.steps.min.js"></script>
    <!-- v1.4.2 -->
    <script src="/backend/vendors/bootstrap-select/dist/js/bootstrap-select.min.js"></script>
    <script src="/backend/vendors/chart.js/src/Chart.bundle.min.js"></script>
    <!-- v1.7.0 -->
    <script src="/backend/vendors/dropify/dist/js/dropify.min.js"></script>

    <!-- Clean UI Scripts -->
    <script src="/backend/common/js/common.js"></script>
    <script src="/backend/common/js/demo.temp.js"></script>
</head>
<body class="theme-default">

<section class="page-content">
<div class="page-content-inner" style="background-image: url(backend/common/img/temp/login/5.jpg)">

    <!-- Login Omega Page -->
    <div class="single-page-block-header">
        <div class="row">
            <div class="col-lg-4">
                <div class="logo">
                    <a href="javascript: history.back();">
                        <img src="/backend/common/img/logo.png" alt="Clean UI Admin Template"/>
                    </a>
                </div>
            </div>            
        </div>
    </div>
    <div class="single-page-block">
        <div class="single-page-block-inner effect-3d-element">
            <div class="blur-placeholder"><!-- --></div>
            <div class="single-page-block-form">
                <h3 class="text-center">
                    <i class="icmn-enter margin-right-10"></i>
                    Login Form
                </h3>
                <br />
                <%= form_for(resource, :as => resource_name, :url => session_path(resource_name), :html => {:class => 'form-login'}) do |f| %>

                <%- flash.each do |name, msg| -%>
                    <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
                <%- end -%>
                    <div class="form-group">
                        <%= f.text_field :email, :class => 'form-control', placeholder: "your email .." %>
                    </div>
                    <div class="form-group">                        
                        <%= f.password_field :password, :class => 'form-control passwor', placeholder: "your pasword .." %>
                    </div>
                    <div class="form-group">
                        <a href="javascript: void(0);" class="pull-right">Forgot Password?</a>
                        <div class="checkbox">
                            <label>
                                <%= f.check_box :remember_me %> <%= f.label :remember_me %>
                                Remember me
                            </label>
                        </div>
                    </div>
                    <div class="form-actions">
                        <button type="submit" class="btn btn-primary width-150">Sign In</button>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
    <%# <div class="single-page-block-footer text-center">
        <ul class="list-unstyled list-inline">
            <li><a href="javascript: void(0);">Terms of Use</a></li>
            <li class="active"><a href="javascript: void(0);">Compliance</a></li>
            <li><a href="javascript: void(0);">Confidential Information</a></li>
            <li><a href="javascript: void(0);">Support</a></li>
            <li><a href="javascript: void(0);">Contacts</a></li>
        </ul>
    </div> %>
    <!-- End Login Omega Page -->

</div>

<!-- Page Scripts -->
<script>
    $(function() {

        // Add class to body for change layout settings
        $('body').addClass('single-page single-page-inverse');

        // Form Validation
        $('#form-validation').validate({
            submit: {
                settings: {
                    inputContainer: '.form-group',
                    errorListClass: 'form-control-error',
                    errorClass: 'has-danger'
                }
            }
        });

        // Show/Hide Password
        $('.password').password({
            eyeClass: '',
            eyeOpenClass: 'icmn-eye',
            eyeCloseClass: 'icmn-eye-blocked'
        });

        // Set Background Image for Form Block
        function setImage() {
            var imgUrl = $('.page-content-inner').css('background-image');

            $('.blur-placeholder').css('background-image', imgUrl);
        };

        function changeImgPositon() {
            var width = $(window).width(),
                    height = $(window).height(),
                    left = - (width - $('.single-page-block-inner').outerWidth()) / 2,
                    top = - (height - $('.single-page-block-inner').outerHeight()) / 2;


            $('.blur-placeholder').css({
                width: width,
                height: height,
                left: left,
                top: top
            });
        };

        setImage();
        changeImgPositon();

        $(window).on('resize', function(){
            changeImgPositon();
        });

        // Mouse Move 3d Effect
        var rotation = function(e){
            var perX = (e.clientX/$(window).width())-0.5;
            var perY = (e.clientY/$(window).height())-0.5;
            TweenMax.to(".effect-3d-element", 0.4, { rotationY:15*perX, rotationX:15*perY,  ease:Linear.easeNone, transformPerspective:1000, transformOrigin:"center" })
        };

        if (!cleanUI.hasTouch) {
            $('body').mousemove(rotation);
        }

    });
</script>
<!-- End Page Scripts -->
</section>

<div class="main-backdrop"><!-- --></div>

</body>
</html>

app/views/partial/_sidebar.html.erb
<nav class="left-menu" left-menu>
    <div class="logo-container">
        <a href="/" class="logo">
            <img src="/backend/common/img/logo.png" alt="Clean UI Admin Template" />
            <img class="logo-inverse" src="/backend/common/img/logo-inverse.png" alt="Clean UI Admin Template" />
        </a>
    </div>
    <div class="left-menu-inner scroll-pane">
        <ul class="left-menu-list left-menu-list-root list-unstyled">
            <li <%= params[:controller] == "homes" ? " class=left-menu-list-active" : " class=left-menu-list" %>>
                <a class="left-menu-link" href="/admins">
                    <i class="left-menu-link-icon icmn-home2"><!-- --></i>
                    <span class="menu-top-hidden">Dashboard</span>
                </a>
            </li>                
            <li class="left-menu-list-separator"><!-- --></li>            
            <li <%= params[:controller] == "invited_guests" ? " class=left-menu-list-active" : " class=left-menu-list" %>>
                <a class="left-menu-link" href="/admin/invited_guests">
                    <i class="left-menu-link-icon icmn-user-plus2"><!-- --></i>
                    <span class="menu-top-hidden">Daftar Undangan</span>
                </a>
            </li>
            <li <%= params[:controller] == "brides" || params[:controller] == "grooms" ? " class=left-menu-list-active" : " class=left-menu-list" %>>
                <a class="left-menu-link" href="/admin/grooms?user_id=<%= current_user.id %>">
                    <i class="left-menu-link-icon icmn-user-plus2"><!-- --></i>
                    <span class="menu-top-hidden">Data Pengantin</span>
                </a>
            </li>
            <li <%= params[:controller] == "reports" ? "  class=left-menu-list-active" : " class=left-menu-list-submenu" %>>
                <a class="left-menu-link" href="javascript: void(0);">
                    <i class="left-menu-link-icon icmn-notebook util-spin-delayed-pseudo"><!-- --></i>
                    Laporan
                </a>                         
                <ul class="left-menu-list list-unstyled">
                    <li>
                        <a class="left-menu-link" href="/reports_transactions">
                            <i class="left-menu-link-icon"><!-- --></i>
                            Penjualan
                        </a>                            
                        <a class="left-menu-link" href="/reports_purchases">
                            <i class="left-menu-link-icon"><!-- --></i>
                            Pembelian
                        </a>                            
                    </li>                    
                </ul>                               
            </li> 

            <li <%= params[:controller] == "users" || params[:controller] == "vendor_types" ? "  class=left-menu-list-active" : " class=left-menu-list-submenu" %>>
                <a class="left-menu-link" href="javascript: void(0);">
                    <i class="left-menu-link-icon icmn-cog util-spin-delayed-pseudo"><!-- --></i>
                    Pengaturan
                </a>                         
                <ul class="left-menu-list list-unstyled">
                    <li>
                        <a class="left-menu-link" href="/admin/users">
                            <i class="left-menu-link-icon"><!-- --></i>
                            Daftar User
                        </a>                                                                           
                    </li>
                    <li>
                        <a class="left-menu-link" href="/admin/user_groups">
                            <i class="left-menu-link-icon"><!-- --></i>
                            Daftar User Group
                        </a>                                                                           
                    </li>                    
                </ul>                               
            </li>                
        </ul>
    </div>
</nav>